---
name: Create release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Retrieve tag name
        id: tag_name
        run: |
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}

      - name: Create tarballs and zips
        if: startsWith(github.ref, 'refs/tags/')
        run: bash ./release.sh $(git describe --tags --abbrev=0)

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            releases/*
